name: WFM_Event_Ingestor_PRD_SRV_95 --- sa-wfm-event-ingestor-svc ---
on:
  workflow_dispatch:
    branches:
      - main # Aqui va la rama
jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_95}} # Clave privada

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOSTNAME_95}} 	# Nombre de host
          username: ${{secrets.SSH_USERNAME_95}} # nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_95}} # Clave privada
          script: |
            echo "### path servidor 8.95 ###"
            cd /adsaenv/adsa/app/adsaweb
            pwd
            ls -lrt 
            echo "###  respaldo del repositorio del servidor ###"
            mv sa-wfm-event-ingestor-svc //adsaenv/adsa/app/adsaweb/sa-wfm-event-ingestor-svc_$(date +'%Y%m%d-%H%M')
            ls -lrt 
            echo '### Clonar el repositorio sa-wfm-event-ingestor-svc ###'
            git clone -b main https://${{secrets.GH_ACCESS_KEY_JALS}}@github.com/joseantonio-lpz/sa-wfm-event-ingestor-svc.git
            ###git clone -b main https://${{secrets.GH_USER_ACCESS_KEY}}@github.com/joseantonio-lpz/sa-wfm-event-ingestor-svc.git            
            echo '### Repositorio clonado sa-wfm-event-ingestor-svc ###' 
            ls -lrt
            sleep 20
            echo '### Detener y eliminar el Contenedor wfm-event-ingestor-app ###'
            docker ps
            docker stop wfm-event-ingestor-app
            sleep 20
            docker rm wfm-event-ingestor-app
            echo '### eliminimar la imagen ###'
            docker images
            sleep 20
            docker rmi wfm-event-ingestor
            docker images
            echo '### Ejecutar el build y el deploy ###'
            cd /adsaenv/adsa/app/adsaweb/sa-wfm-event-ingestor-svc
            ls -lrt
            docker build -t wfm-event-ingestor .
            sleep 40
            ### docker run -d -p 5102:8080 --name wfm-event-ingestor-app wfm-event-ingestor
            docker run -d -p 5102:8080 -e ASPNETCORE_ENVIRONMENT=Production -v dataprotection-keys:/root/.aspnet/DataProtection-Keys --name wfm-event-ingestor-app wfm-event-ingestor
            sleep 20
            echo '### contenedores corriendo ###'
            docker ps -a
            echo '###### Enviar correo ######'
            cd /home/GIT
            docker ps -a > deploy.txt
            mail -s "Deploy realizado proyecto WFM PRD -- wfm-event-ingestor-app" joseantonio.lopez@seccionamarilla.com < deploy.txt
            echo '###### fin del workflow ######'          
