name: WFM_External_Event_Ingestor_PRD_SRV_95 --- sa-external-event-ingestor-svc ---
on:
  workflow_dispatch:
    branches:
      - main # Aqui va la rama
jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_95}} # Clave privada

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOSTNAME_95}} 	# Nombre de host
          username: ${{secrets.SSH_USERNAME_95}} # nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_95}} # Clave privada
          script: |
            echo "### path servidor 8.95 ###"
            cd /adsaenv/adsa/app/adsaweb
            pwd
            ls -lrt 
            echo "###  respaldo del repositorio del servidor ###"
            mv sa-wfm-event-ingestor-svc /adsaenv/adsa/app/adsaweb/sa-wfm-event-ingestor-svc_$(date +'%Y%m%d-%H%M')
            ls -lrt 
            echo '### Clonar el repositorio sa-wfm-event-ingestor-svc ###'
            git clone -b main https://${{secrets.GH_ACCESS_KEY}}@github.com/jeacor/sa-external-event-ingestor-svc.git
            echo '### Repositorio clonado ###' 
            ls -lrt
            sleep 40
            echo '### Detener y eliminar el Contenedor wfm-producer ###'
            docker ps
            docker stop wfm-producer
            sleep 40
            docker rm wfm-producer
            echo '### elimininar la imagen ###'
            docker images
            sleep 40
            docker rmi wfm-producer
            docker images
            echo '### Ejecutar el build y el deploy ###'
            cd /adsaenv/adsa/app/adsaweb/sa-wfm-event-ingestor-svc/WFM.DataHub
            ls -lrt
            docker build -t wfm-producer .
            sleep 40
            docker run -d -p 5100:8080 -v dataprotection-keys:/root/.aspnet/DataProtection-Keys --name wfm-producer-app wfm-producer
            sleep 20
            echo '### contenedores corriendo ###'
            docker ps -a
             echo '###### Enviar correo ######'
            cd /adsaenv/adsa/app/adsaweb
            docker ps -a > deploy.txt
            mail -s "Deploy realizado proyecto WFM_Event_Ingestor_PRD -- sa-external-event-ingestor-svc" joseantonio.lopez@seccionamarilla.com < deploy.txt
            echo '###### fin del workflow ######''     
